site_name: Spectrum Analyzer
site_description: 'Create a sound spectrum analyzer using a Raspberry Pi Pico 2 and a OLED display.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/spectrum-analyzer/'
repo_url: 'https://github.com/dmccreary/spectrum-analyzer'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - About: about.md
  - Research: research.md
  - Course Description: course-description.md
  - Setup:
    - Introduction: setup/index.md
    - Hardware: setup/hardware.md
    - Desktop: setup/desktop.md
    - Connections: setup/connections.md
  - Lessons: 
      - Introduction: lessons/index.md
      - Test Sound: lessons/01-test-incoming-sound.md
      - Display Scroll: lessons/03-display-scroll.md
      - Optimization: lessons/04-optimizing-fft-speed.md
      - Frequency Window: lessons/05-frequency-shift.md
      - Peak Frequency: lessons/06-peak-frequency.md
      - Further Speedups: lessons/07-speedups.md
      - Adding Timers: lessons/08-adding-timers.md
      - Assembler FFT: lessons/09-assembler-function.md
      - Future Work: lessons/10-future-improvements.md
      - DSP Instructions: lessons/50-dsp-instructions.md
      - FFT: lessons/30-fft.md
      - FFT Butterfly: lessons/31-fft-butterfly.md
  - MicroSims: 
    - Introduction: sims/index.md
    - Base and Treble: sims/base-and-treble/index.md
    - Tone Generator: sims/tone-generator/index.md
    - Waveform Types: sims/waveform-types/index.md
    - FFT Butterfly: sims/fft-butterfly/index.md
    - Templates: sims/templates/index.md
  - Project Ideas: project-ideas.md
  - Commercial Uses of FFTs: commercial-fft.md
  - Feedback: feedback.md
  - License: license.md
  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - Contact: contact.md
 
# Dan's Microsite Standards from here down

theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'navy'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
  features:
    - content.footnote.tooltips
plugins:
  - search
  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
  - footnotes
extra_css:
   - css/extra.css
extra_javascript:
    - js/extra.js
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX